import { migrate } from 'drizzle-orm/better-sqlite3/migrator';
import type { Db } from './client';

/** Applies any pending SQL migrations from `migrationsFolder` (generated by drizzle-kit). */
export function runMigrations(db: Db, migrationsFolder: string): void {
  migrate(db, { migrationsFolder });
}
